### ISSUE TITLE
Relative Path not being included

### ISSUE THREAD

**Issue by DaveArthur** [julianlam/nodebb-plugin-google-analytics#13]
Hey, Looking at the Overview in Google analytics I'm noticing I'm not getting the full path most of the time. 
![analyticspath](https://cloud.githubusercontent.com/assets/5874591/6310487/4bd40c58-b94f-11e4-8f67-5b306b15439d.JPG)
If it on the main page the /forum/ shows up but not else where. The /bp/... is ok
I'm more concerned with google trying to follow the links back and finding a broken url

**Comment by julianlam** [comment]
Hm, that is a good point. Should be an easy fix...

**Comment by julianlam** [comment]
Can you do a quick test for me?

Change [this line](https://github.com/julianlam/nodebb-plugin-google-analytics/blob/master/lib/client.js#L17) to pass in `RELATIVE_PATH + data.url` instead of just `data.url`, and let me know if that fixes the issue?

**Comment by julianlam** [comment]
Fixed by #14

**Comment by DaveArthur** [comment]
Yer that ish fixed it needed the extra / tho
