### ISSUE TITLE
Tracking ID not in page source code

### ISSUE THREAD

**Issue by henrywright** [julianlam/nodebb-plugin-google-analytics#16]
Hey guys,

Installed 0.5.3 today then went through each step in [README.md](https://github.com/julianlam/nodebb-plugin-google-analytics/blob/master/README.md). Everything went smoothly until step 5. When I looked at my site's source code, my tracking ID isn't there.

I checked the NodeBB logs, nothing in there related to this.

Using NodeBB 0.7.2, Nginx, Ubuntu 14.04 VPS. Viewing on the Chromium browser.

**Comment by julianlam** [comment]
How are you viewing the source? It is added after the page is loaded, and won't show up in the html sent by nodebb

**Comment by henrywright** [comment]
I just hit Ctrl + U together and took a look at the page source. I'm guessing that's not the way to verify in this case?

**Comment by julianlam** [comment]
Best way to verify is to go to the Live Analytics on GA and confirm that the plugin can track you navigating across the site.

**Comment by henrywright** [comment]
Thanks. I went to the real-time tab and can see it records my visit when I navigate around the forum. The thing that most confused me was going to Tracking Info > Tracking Code, it reads:

> Status: __Tracking Not Installed__
The Google Analytics tracking code has not been detected on your website's home page. For Analytics to function, you or your web administrator must add the code to each page of your website.

Actually, it still does read that (last check was Aug 16, 2015 4:06:32 PM PDT). Not sure if that matters?

**Comment by julianlam** [comment]
That might always be the case as the tracking code is not added on cold
page loads.

**Comment by henrywright** [comment]
Right! Thanks for taking the time to reply on this one, appreciate it!
