### ISSUE TITLE
set up requirement warning does not go away in 1.18.6

### ISSUE THREAD

**Issue by AliCihan** [julianlam/nodebb-plugin-google-analytics#36]
Hi @julianlam , I have explained the situation here:

https://community.nodebb.org/post/86505

**Comment by barisusakli** [comment]
What version of this plugin are you using? https://github.com/julianlam/nodebb-plugin-google-analytics/commit/5a0a750c84a051af8ace77811881560e17e1dc95 this commit seems to be a fix for the admin notice.

**Comment by AliCihan** [comment]
fixed in 0.6.1
