### ISSUE TITLE
Analytics ID Not Being Picked Up

### ISSUE THREAD

**Issue by shaneedwards** [julianlam/nodebb-plugin-google-analytics#9]
After activating the plugin I enter my analytics ID, but when I load the system as a user I am seeing a console error stating that it cannot find the analytics ID:

![image](https://cloud.githubusercontent.com/assets/7059852/3714571/b2a46c5e-15b0-11e4-8ffd-ec6efd0c1573.png)

**Comment by aggied** [comment]
Not sure what I'm doing wrong here, but can't get the analytics to pickup. I'm on version 0.7 (latest) of NodeBB, and version 0.5.3 of this plugin. Any thoughts? I've rebooted many times after saving the code in ACP.

**Comment by julianlam** [comment]
Hi @aggied, this plugin is still cleared for use in the latest NodeBB version, so I can't imagine what could be going wrong. Are you pasting your `UA-*` number into the plugin settings?
